### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by wwehner** [icl-rocketry/PropulsionSystemModel#2]
I'm trying to digest this model. Is there any documentation you could point out associated with this project? Papers, dissertations, presentations, etc?

**Comment by storm345** [comment]
Hi, there are annotations and comments throughout the model and code which seek to explain what is going on to enough detail for somebody who understands about simulink, matlab and the basic principles of a hybrid motor. We currently don't have any other supporting documentation, though if you wish to contribute any feel free. We may create some more guidance in the future.
